### ISSUE TITLE
No HTML based UI for Reversing Strings.

### ISSUE THREAD

**Issue by thegooglerlm10** [logeshpaul/javascript-coding-challenges#1]
@logeshpaul . Only a readme file exits for reversing arrays . Should a create a simple UI with buttons labelled by the method names?

**Comment by logeshpaul** [comment]
Hey @thegooglerlm10 Tat's a good suggestion. Will create and update it here.

**Comment by logeshpaul** [comment]
Resolved - http://logeshpaul.github.io/javascript-coding-challenges/demo/reverse-string.html
